# Generated by Django 5.0.7 on 2024-08-16 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('map', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('nick_name', models.CharField(default='Unknown Nickname', max_length=100)),
                ('real_name', models.CharField(default='Unknown Real Name', max_length=100)),
                ('nationality', models.CharField(default='Unknown Nationality', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('bio', models.TextField(default='No biography available.')),
                ('image_url', models.URLField(blank=True, default='')),
                ('steam_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winningTeam', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('success_criteria', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=1)),
                ('isWarmup', models.BooleanField(default=False)),
                ('winningSide', models.CharField(default='Unknown', max_length=100)),
                ('roundEndReason', models.CharField(default='Unknown', max_length=100)),
                ('bombPlant', models.BooleanField(default=False)),
                ('t_startEquipmentValue', models.IntegerField(default=0)),
                ('ct_startEquipmentValue', models.IntegerField(default=0)),
                ('t_endEquipmentValue', models.IntegerField(default=0)),
                ('ct_endEquipmentValue', models.IntegerField(default=0)),
                ('match_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.match')),
            ],
        ),
        migrations.CreateModel(
            name='Kills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attackerSide', models.CharField(default='Unknown', max_length=100, null=True)),
                ('victimSide', models.CharField(default='Unknown', max_length=100, null=True)),
                ('isHeadshot', models.BooleanField()),
                ('distance', models.FloatField(default=0.0)),
                ('isTrade', models.BooleanField()),
                ('weapon', models.CharField(default='Unknown', max_length=100, null=True)),
                ('weaponClass', models.CharField(default='Unknown', max_length=100, null=True)),
                ('tick', models.IntegerField(default=0)),
                ('round_time', models.CharField(max_length=10)),
                ('assister_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assister', to='stats.player')),
                ('attacker_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacker', to='stats.player')),
                ('victim_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victim', to='stats.player')),
                ('round_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.round')),
            ],
        ),
        migrations.CreateModel(
            name='BombEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('ticks_since_round_start', models.IntegerField(default=0)),
                ('ticks_since_freeze_time_end', models.IntegerField(default=0)),
                ('ticks_since_bomb_plant', models.IntegerField(default=0)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.round')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='series_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.series'),
        ),
        migrations.CreateModel(
            name='SeriesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('created_time', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.user')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('kills_per_round', models.FloatField(default=0.0)),
                ('deaths_per_round', models.FloatField(default=0.0)),
                ('kd_ratio', models.FloatField(default=0.0)),
                ('headshot_percentage', models.FloatField(default=0.0)),
                ('total_kills', models.IntegerField(default=0)),
                ('total_deaths', models.IntegerField(default=0)),
                ('damage_per_round', models.FloatField(default=0.0)),
                ('rounds_played', models.IntegerField(default=0)),
                ('maps_played', models.IntegerField(default=0)),
                ('win_percentage', models.FloatField(default=0.0)),
                ('entry_kills', models.IntegerField(default=0)),
                ('adr', models.FloatField(default=0.0)),
                ('kast', models.FloatField(default=0.0)),
                ('impact', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tactic A', max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
                ('maps', models.ManyToManyField(related_name='map_name', to='stats.map')),
                ('rounds', models.ManyToManyField(related_name='round_id', to='stats.round')),
                ('type', models.ManyToManyField(related_name='type_id', to='stats.strategytype')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('team_img_url', models.URLField(blank=True)),
                ('players', models.ManyToManyField(related_name='player_team', to='stats.player')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='winningTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_a_matches', to='stats.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_b_matches', to='stats.team'),
        ),
        migrations.CreateModel(
            name='SeriesReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=10000)),
                ('replay_time_code', models.TimeField()),
                ('created_time', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('series_review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.seriesreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.user')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.user'),
        ),
    ]
