# Generated by Django 5.0.7 on 2024-08-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kills',
            name='isTrade',
        ),
        migrations.AddField(
            model_name='kills',
            name='traded_by',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
