# Generated by Django 5.0.7 on 2024-08-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_kills_istrade_kills_traded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tick_rate',
            field=models.IntegerField(default=64),
        ),
        migrations.CreateModel(
            name='BombEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('z', models.FloatField(default=0.0)),
                ('ticks_since_round_start', models.IntegerField(default=0)),
                ('ticks_since_freeze_time_end', models.IntegerField(default=0)),
                ('ticks_since_bomb_plant', models.IntegerField(default=0)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.round')),
            ],
        ),
        migrations.DeleteModel(
            name='BombEvents',
        ),
    ]
