# Generated by Django 5.0.7 on 2024-07-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
