# Generated by Django 5.0.7 on 2024-08-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('success_criteria', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='bombPlant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='ct_endEquipmentValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='ct_startEquipmentValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='t_endEquipmentValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='t_startEquipmentValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='type',
            field=models.ManyToManyField(related_name='type_id', to='stats.strategytype'),
        ),
    ]
