# Generated by Django 5.0.7 on 2024-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(default='No biography available.'),
        ),
        migrations.AddField(
            model_name='player',
            name='damage_per_round',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='deaths_per_round',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='entry_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='headshot_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='kd_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='kills_per_round',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='maps_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='Unknown Nationality', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='nick_name',
            field=models.CharField(default='Unknown Nickname', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='real_name',
            field=models.CharField(default='Unknown Real Name', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='rounds_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='win_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='team_img_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='steam_id',
            field=models.CharField(default='Unknown Steam ID', max_length=50),
        ),
    ]
