# Generated by Django 5.0.7 on 2024-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_match_tick_rate_bombevent_delete_bombevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='bestOf',
            field=models.IntegerField(default=1),
        ),
    ]
