# Generated by Django 5.0.7 on 2024-07-31 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_player_name_player_age_player_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winningTeam', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='damage_per_round',
        ),
        migrations.RemoveField(
            model_name='player',
            name='deaths_per_round',
        ),
        migrations.RemoveField(
            model_name='player',
            name='entry_kills',
        ),
        migrations.RemoveField(
            model_name='player',
            name='headshot_percentage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kd_ratio',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kills_per_round',
        ),
        migrations.RemoveField(
            model_name='player',
            name='maps_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rounds_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_deaths',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_kills',
        ),
        migrations.RemoveField(
            model_name='player',
            name='win_percentage',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='kills',
        ),
        migrations.AddField(
            model_name='match',
            name='map',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='stat',
            name='damage_per_round',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='deaths_per_round',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='entry_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='headshot_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='kd_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='kills_per_round',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='maps_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='rounds_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='total_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='win_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_a_matches', to='stats.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_b_matches', to='stats.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='player_team', to='stats.player'),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=1)),
                ('isWarmup', models.BooleanField(default=False)),
                ('winningSide', models.CharField(default='Unknown', max_length=100)),
                ('roundEndReason', models.CharField(default='Unknown', max_length=100)),
                ('match_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.match')),
            ],
        ),
        migrations.CreateModel(
            name='Kills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attackerSide', models.CharField(default='Unknown', max_length=100)),
                ('victimSide', models.CharField(default='Unknown', max_length=100)),
                ('isHeadshot', models.BooleanField()),
                ('distance', models.FloatField()),
                ('isTrade', models.BooleanField()),
                ('weapon', models.CharField(default='Unknown', max_length=100)),
                ('weaponClass', models.CharField(default='Unknown', max_length=100)),
                ('assister_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assister', to='stats.player')),
                ('attacker_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacker', to='stats.player')),
                ('victim_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victim', to='stats.player')),
                ('round_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.round')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='series_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.series'),
        ),
    ]
