# Generated by Django 5.0.7 on 2024-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_series_bestof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombevent',
            name='ticks_since_bomb_plant',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
