# Generated by Django 5.0.7 on 2024-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_series_remove_player_damage_per_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='attackerSide',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kills',
            name='victimSide',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kills',
            name='weapon',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kills',
            name='weaponClass',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
    ]
