# Generated by Django 5.0.7 on 2024-08-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_seriesreviewcomment_user_alter_player_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='bestOf',
            new_name='best_of',
        ),
        migrations.RemoveField(
            model_name='series',
            name='winningTeam',
        ),
        migrations.AddField(
            model_name='series',
            name='team_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_a_series', to='stats.team'),
        ),
        migrations.AddField(
            model_name='series',
            name='team_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_b_series', to='stats.team'),
        ),
        migrations.AddField(
            model_name='series',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_team_series', to='stats.team'),
        ),
    ]
