# Generated by Django 5.0.7 on 2024-08-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_kills_attackerside_alter_kills_victimside_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='adr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='impact',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='kast',
            field=models.FloatField(default=0.0),
        ),
    ]
