# Generated by Django 5.0.7 on 2024-08-20 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_rename_bestof_series_best_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='series_id',
        ),
        migrations.AddField(
            model_name='match',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='stats.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_series', to='stats.team'),
        ),
        migrations.AlterField(
            model_name='series',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_series', to='stats.team'),
        ),
    ]
