# Generated by Django 5.0.7 on 2024-08-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_stat_adr_stat_impact_stat_kast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='adr',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='kast',
        ),
    ]
