# Generated by Django 5.0.7 on 2024-08-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_remove_match_series_id_match_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='ticks',
            field=models.JSONField(null=True),
        ),
    ]
