# Generated by Django 5.0.7 on 2024-08-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_remove_stat_adr_remove_stat_impact_remove_stat_kast'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='adr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='impact',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='kast',
            field=models.FloatField(default=0.0),
        ),
    ]
