# Generated by Django 5.0.7 on 2024-08-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_uploadeddemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddemo',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demos', to='stats.match'),
        ),
    ]
