# Generated by Django 5.0.7 on 2024-08-26 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_uploadeddemo_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddemo',
            name='match',
        ),
        migrations.AddField(
            model_name='uploadeddemo',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demos', to='stats.series'),
        ),
    ]
