# Generated by Django 5.0.7 on 2024-08-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.round'),
        ),
    ]
