# Generated by Django 5.0.7 on 2024-09-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_bombevent_tick_grenade_playertick_weaponfires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='stratCanvas',
            field=models.JSONField(null=True),
        ),
    ]
