# Generated by Django 5.0.7 on 2024-09-10 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0021_alter_strategy_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddemo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='uploadeddemo',
            name='series',
        ),
        migrations.RemoveField(
            model_name='uploadeddemo',
            name='team',
        ),
        migrations.AddField(
            model_name='uploadeddemo',
            name='hash',
            field=models.CharField(default='', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='uploadeddemo',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.match'),
        ),
        migrations.AlterField(
            model_name='uploadeddemo',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
