# Generated by Django 5.0.7 on 2024-09-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_remove_uploadeddemo_id_remove_uploadeddemo_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clanName', models.CharField(default='Unknown', max_length=100)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_lineout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_a_lineout', to='stats.matchplayers'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_lineout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_b_lineout', to='stats.matchplayers'),
        ),
    ]
