# Generated by Django 5.0.7 on 2024-09-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_matchplayers_match_team_a_lineout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_a_lineout',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_b_lineout',
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clanName', models.CharField(default='Unknown', max_length=100)),
                ('players', models.ManyToManyField(related_name='player_lineup', to='stats.player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_lineup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_a_lineup', to='stats.lineup'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_lineup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_b_lineup', to='stats.lineup'),
        ),
        migrations.AlterField(
            model_name='round',
            name='winningTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.lineup'),
        ),
        migrations.DeleteModel(
            name='MatchPlayers',
        ),
    ]
