# Generated by Django 5.0.7 on 2024-09-11 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_remove_match_team_a_lineout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddemo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='uploadeddemo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uploadeddemo',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='uploadeddemo',
            name='uploaded_by',
        ),
        migrations.CreateModel(
            name='UploadedDemoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='demos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('demo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.uploadeddemo')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
