# Generated by Django 5.0.7 on 2024-09-12 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_remove_stat_entry_kills_remove_stat_maps_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddemofile',
            name='status',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadeddemofile',
            name='file',
            field=models.FileField(upload_to='demos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dem'])]),
        ),
    ]
