# Generated by Django 5.0.7 on 2024-09-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0028_uploadeddemofile_status_alter_uploadeddemofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nick_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='real_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
