# Generated by Django 5.0.7 on 2024-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0029_alter_player_nationality_alter_player_nick_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='best_of',
        ),
        migrations.RemoveField(
            model_name='series',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='series',
            name='team_b',
        ),
        migrations.RemoveField(
            model_name='series',
            name='winning_team',
        ),
        migrations.AddField(
            model_name='series',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='stats.team'),
        ),
        migrations.AddField(
            model_name='series',
            name='title',
            field=models.TextField(default='Series'),
        ),
    ]
