# Generated by Django 5.0.7 on 2024-09-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_remove_series_best_of_remove_series_team_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_b',
        ),
        migrations.RemoveField(
            model_name='series',
            name='teams',
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='stats.team'),
        ),
    ]
