# Generated by Django 5.0.7 on 2024-09-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0031_remove_match_team_a_remove_match_team_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddemofile',
            name='options',
            field=models.JSONField(null=True),
        ),
    ]
