# Generated by Django 5.0.7 on 2024-09-15 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0033_post_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.post'),
        ),
    ]
