# Generated by Django 5.0.7 on 2024-09-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0035_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.post'),
        ),
    ]
