# Generated by Django 5.0.7 on 2024-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0037_stat_total_assists'),
    ]

    operations = [
        migrations.AddField(
            model_name='kills',
            name='assisterX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kills',
            name='assisterY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kills',
            name='assisterZ',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kills',
            name='attackerX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kills',
            name='attackerY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kills',
            name='attackerZ',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kills',
            name='victimX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kills',
            name='victimY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kills',
            name='victimZ',
            field=models.FloatField(default=0.0),
        ),
    ]
