# Generated by Django 5.0.7 on 2024-09-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0038_kills_assisterx_kills_assistery_kills_assisterz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='acknowledgements',
            field=models.ManyToManyField(blank=True, related_name='acknowledged_by', to='stats.player'),
        ),
    ]
