# Generated by Django 5.0.7 on 2024-09-19 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0040_alter_kills_assisterx_alter_kills_assistery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
